# Generated by Django 4.2 on 2023-07-16 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company Info', 'verbose_name_plural': 'Company Info'},
        ),
    ]
